application: phylobox
version: 2-0
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/gfx/favicon.ico
  upload: static/gfx/favicon.ico

- url: /static
  static_dir: static
  
- url: /admin/.*
  script: app.py
  login: admin
  
- url: /cron/.*
  script: cron.py
  login: admin
  
- url: /task/.*
  script: task.py
  
- url: /api/.*
  script: api.py
  
- url: /.*
  script: app.py
  
  
